const init=()=>{
    const mobileNavToggle=document.getElementById('mobileNavToggle'), siteNavLinks=document.getElementById('siteNavLinks');
    mobileNavToggle.addEventListener('click',()=>{const open=mobileNavToggle.getAttribute('aria-expanded')==='true';mobileNavToggle.setAttribute('aria-expanded',String(!open));siteNavLinks.classList.toggle('open',!open)});
    document.querySelectorAll('#siteNavLinks a').forEach(a=>a.addEventListener('click',()=>{if(innerWidth<=850){mobileNavToggle.setAttribute('aria-expanded','false');siteNavLinks.classList.remove('open')}}));
    document.querySelectorAll('.faq-button').forEach(btn=>btn.addEventListener('click',()=>{const ans=document.getElementById(btn.getAttribute('aria-controls')),open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));ans.classList.toggle('open',!open)}));
    const searchItems=[
      ['Course Substitution Form','Frequently-Used Forms','Submit or locate information about academic course substitution requests.','course substitution substitution form advising transfer equivalency student degree','#forms'],
      ['CARE Referral Form','Frequently-Used Forms','Report a student concern using the college’s CARE referral process.','care referral student concern support','#forms'],
      ['Early Alert Form','Frequently-Used Forms','Connect students with support through the Early Alert process.','early alert student success referral attendance','#forms'],
      ['Professional Development Forms','Frequently-Used Forms','Forms and resources for faculty professional development.','professional development workshop training','#forms'],
      ['Travel Expense and IPR Forms','Frequently-Used Forms','Travel, reimbursement, and IPR forms and instructions.','travel expense reimbursement ipr faculty chair','#forms'],
      ['Syllabus Templates','Center for Teaching Excellence','Current syllabus templates and related course-design guidance.','syllabus template course outline teaching','#teaching-excellence'],
      ['Assessment Plan Templates','Center for Teaching Excellence','Assessment-plan documents, templates, rubrics, and guidance.','assessment plan template rubric outcomes','#teaching-excellence'],
      ['ADA Materials and Accessibility Resources','Center for Teaching Excellence','Accessibility checklists, ADA guidance, and how-to videos.','ada accessibility checklist captions udl','#teaching-excellence'],
      ['Library and VR Lab','Center for Teaching Excellence','Connect with instructional partners in the Library and YCCC VR Lab.','library vr lab virtual reality immersive','#teaching-excellence'],
      ['Faculty Handbooks','Faculty Resources','Handbooks and guidance for full-time, part-time, and adjunct faculty.','faculty handbook full time part time adjunct','#faculty-resources'],
      ['Advising How-Tos','Faculty Resources','Step-by-step guides and resources for academic advising.','advising how to degree audit registration advisee','#faculty-resources'],
      ['Class Cancellation Procedures','Faculty Resources','Procedures and communication guidance for cancelling a class.','cancel class cancellation emergency weather','#faculty-resources'],
      ['MCCS Academic Policies','Policies','Maine Community College System academic policies, standards, and procedures.','mccs academic policy procedures standards','#policies'],
      ['Academic Affairs Help and FAQ','Help','Frequently asked questions and options for contacting Academic Affairs.','help faq contact assistance support','#help']
    ];
    const openBtn=document.getElementById('searchOpenButton'),closeBtn=document.getElementById('searchCloseButton'),overlay=document.getElementById('searchOverlay'),input=document.getElementById('overlaySearchInput'),results=document.getElementById('searchResults');let prior=null;
    function render(q=''){const x=q.trim().toLowerCase(),m=x?searchItems.filter(i=>i.join(' ').toLowerCase().includes(x)):searchItems.slice(0,7);results.innerHTML='';const s=document.createElement('div');s.className='search-status';s.textContent=x?`${m.length} ${m.length===1?'result':'results'} for “${q.trim()}”`:'Suggested resources';results.append(s);if(!m.length){const d=document.createElement('div');d.className='empty-search';d.textContent='No matching resources found. Try “course substitution,” “advising,” “syllabus,” “Early Alert,” “ADA,” or “assessment.”';results.append(d);return}m.forEach(i=>{const a=document.createElement('a');a.className='search-result';a.href=i[4];a.innerHTML=`<span class="result-category"></span><span class="result-title"></span><span class="result-description"></span>`;a.children[0].textContent=i[1];a.children[1].textContent=i[0];a.children[2].textContent=i[2];a.addEventListener('click',closeSearch);results.append(a)})}
    function openSearch(){prior=document.activeElement;overlay.classList.add('open');document.body.classList.add('no-scroll');input.value='';render();setTimeout(()=>input.focus(),50)}function closeSearch(){overlay.classList.remove('open');document.body.classList.remove('no-scroll');if(prior)prior.focus()}
    openBtn.addEventListener('click',openSearch);closeBtn.addEventListener('click',closeSearch);input.addEventListener('input',e=>render(e.target.value));overlay.addEventListener('click',e=>{if(e.target===overlay)closeSearch()});
    const launcher=document.getElementById('chatLauncher'),win=document.getElementById('chatWindow'),chatClose=document.getElementById('chatCloseButton'),form=document.getElementById('chatForm'),chatInput=document.getElementById('chatInput'),messages=document.getElementById('chatMessages');
    function openChat(){win.classList.add('open');launcher.setAttribute('aria-expanded','true');setTimeout(()=>chatInput.focus(),50)}function closeChat(){win.classList.remove('open');launcher.setAttribute('aria-expanded','false');launcher.focus()}function add(text,user=false){const d=document.createElement('div');d.className=user?'message user':'message';d.textContent=text;messages.append(d);messages.scrollTop=messages.scrollHeight}function reply(t){t=t.toLowerCase();if(t.includes('substitution'))return'The Course Substitution Form is listed under Frequently-Used Forms. Connect that link to the official YCCC form and approval instructions.';if(t.includes('advis'))return'Look in Faculty Resources for Advising How-Tos, including degree audit, registration, referral, and common advising guidance.';if(t.includes('early alert')||t.includes('care'))return'CARE Referral and Early Alert resources are in Frequently-Used Forms. Use the official YCCC links there for student-support reporting.';if(t.includes('syllabus')||t.includes('assessment')||t.includes('rubric'))return'The Center for Teaching Excellence includes syllabus templates, assessment-plan materials, rubrics, workshop resources, and instructional support.';if(t.includes('ada')||t.includes('accessib'))return'For accessibility guidance, use the Center for Teaching Excellence for ADA checklists, videos, and accessible course-design resources.';if(t.includes('travel')||t.includes('ipr')||t.includes('expense'))return'Travel Expense and IPR materials are in Frequently-Used Forms, including instructions for faculty chairs.';if(t.includes('policy')||t.includes('mccs'))return'Use the MCCS Academic Policies tile for policies, standards, and procedure information.';return'I can help route you to Academic Affairs resources. Ask about course substitutions, advising, forms, Early Alert, accessibility, assessment, faculty handbooks, or MCCS policies.'}
    launcher.addEventListener('click',()=>win.classList.contains('open')?closeChat():openChat());chatClose.addEventListener('click',closeChat);form.addEventListener('submit',e=>{e.preventDefault();const t=chatInput.value.trim();if(!t)return;add(t,true);chatInput.value='';setTimeout(()=>add(reply(t)),300)});
    document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(overlay.classList.contains('open'))closeSearch();else if(win.classList.contains('open'))closeChat()}});
  });

if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",init)}else{init()}
